image: clojure:alpine

before_script:
    - apk add --update git
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - lein deps

tests:
  stage: test
  script:
    - lein test